name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: quicklinks-staging
  REGION: asia-south1
  SPRING_CLOUD_GCP_PROJECT_ID: ${{ vars.SPRING_CLOUD_GCP_PROJECT_ID }}
  SPRING_CLOUD_GCP_FIRESTORE_DATABASE_ID: ${{ vars.SPRING_CLOUD_GCP_FIRESTORE_DATABASE_ID }}
  GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID}}
  GOOGLE_CLIENT_SECRET: ${{ vars.GOOGLE_CLIENT_SECRET}}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --source . \
            --platform managed \
            --region $REGION \
            --set-env-vars SPRING_CLOUD_GCP_PROJECT_ID=$SPRING_CLOUD_GCP_PROJECT_ID,SPRING_CLOUD_GCP_FIRESTORE_DATABASE_ID=$SPRING_CLOUD_GCP_FIRESTORE_DATABASE_ID,GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET \
            --allow-unauthenticated